name: Daily run

on: 
  schedule:
    # 11:00 UTC = 12:00 CET (winter)
        # Summer time (CEST = UTC+2): 10:00 UTC
    - cron: '0 10 * 4-10 *'  # April–October inclusive

    # Winter time (CET = UTC+1): 11:00 UTC
    - cron: '0 11 * 1-3,11,12 *'  # January–March + November–December
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore & Build
        run: dotnet build ./JobScraper.csproj --configuration Release

      - name: Run scraper
        env: 
          ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}
          SmsSettings__AccountSID:            ${{ secrets.ACCOUNTSID }}
          SmsSettings__AuthToken:             ${{ secrets.AUTHTOKEN }}
          SmsSettings__SenderNumber:          ${{ secrets.SENDERNUMBER }}
          SmsSettings__RecipientNumber:       ${{ secrets.RECIPIENTNUMBER }}
        run: dotnet run --project ./JobScraper/JobScraper.csproj --configuration Release
      
      
